version: '3.8'

services:
  web:
    build: .
    container_name: my-website
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/usr/share/nginx/html
      - /etc/letsencrypt/live/lameute.cm/fullchain.pem:/etc/letsencrypt/live/lameute.cm/fullchain.pem
      - /etc/letsencrypt/live/lameute.cm/privkey.pem:/etc/letsencrypt/live/lameute.cm/privkey.pem
    restart: always